# Usage:
#   kind create cluster --config hack/kind-config.yaml --image kindest/node:v1.14.3
#   export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
#   kubectl apply -f hack/cert-manager.yaml
#   make deploy
# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "CustomResourceWebhookConversion=true"
  scheduler:
    extraArgs:
      "feature-gates": "CustomResourceWebhookConversion=true"
  controllerManager:
    extraArgs:
      "feature-gates": "CustomResourceWebhookConversion=true"
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "CustomResourceWebhookConversion=true"
# 1 control plane node and 3 workers
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
